server:
    port: 8000
---

logging:
   config: 
     classpath: logback.xml 

---  

spring:
  profiles.active: product

---  

spring: 
  profiles: develop
  thymeleaf: 
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1/acc
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    schema: importMysql.sql
    initialize: false
    
---
spring:
  profiles: product
  thymeleaf: 
    cache: false
  datasource:
    url: jdbc:oracle:thin:@192.168.1.113:1521:XE
    username: GUAN
    password: guan2016
    driver-class-name: oracle.jdbc.driver.OracleDriver
    schema: importMysql.sql
    initialize: false
  
org: 
  mybatis:
    spring:
      SqlSessionTemplate:
        scope: prototype


    
    

    