server:
    port: 8000


logging:
  level:
    root: INFO
    sample:
      mybatis:
        mapper: TRACE
  config:
    classpath: logging-config.xml
  file: police.log
  
  

spring:
  thymeleaf: 
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1/acc
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    schema: import.sql
    initialize: true
    
    

    